### ISSUE TITLE
This driver does not support retrieving URLs.

### ISSUE THREAD

**Issue by chris0203** [Azure-OSS/azure-storage-php-adapter-laravel#5] opened 2024-11-08 10:45 UTC
Hi there,

I just update to new version and got this error when I use

```php
Storage::disk('azure')->url($sd->media_path);
```

**Comment by brecht-vermeersch** [comment] 2024-11-08 10:47
Duplicate of https://github.com/Azure-OSS/azure-storage-php-adapter-laravel/issues/1

**Comment by brecht-vermeersch** [comment] 2024-11-08 10:49
I will add something to the docs about this

**Closed** 2024-11-12 11:58 UTC
